### ISSUE TITLE
Alfred 3 compatibility

### ISSUE THREAD

**Issue by dvcrn** [orta/Alfred-Emoji-Snippets#1]
Thanks for creating this!

I noticed that when importing the snippets into alfred 3, the resulting snippet list is just blank

**Comment by orta** [comment]
ah yeah, couldn't figure out why, I built this repo to show it to the alfred team: https://twitter.com/orta/status/732678207032459266

**Comment by philtr** [comment]
Ran across this on Product Hunt: http://joelcalifa.com/blog/alfred-emoji-snippet-pack/. Seemed to install properly 🤔

**Comment by orta** [comment]
Perfect, will change the README to this

**Comment by dvcrn** [comment]
It'd still be interesting to find out why the generated snippets here didn't work
